export const services = [
    {
        id: 1,
        title: 'Foam-jet service (2 ACs)',
        badge: '2 ACs PACK',
        image: '/images/ac2.jpg',
        rating: 4.77,
        reviews: '1.7M',
        price: 998,
        originalPrice: 1198,
        perAcPrice: 499,
        timeRequired: '1 hr 30 mins',
        details: [
            'Applicable for both window or split ACs',
            'Indoor unit deep cleaning with foam & jet spray',
        ],
        category: 0,
    },
    {
        id: 2,
        title: 'Foam-jet service (3 ACs)',
        badge: '3 ACs PACK',
        image: '/images/ac3.jpg',
        rating: 4.77,
        reviews: '1.7M',
        price: 1497,
        originalPrice: 1797,
        perAcPrice: 499,
        timeRequired: '2 hrs 15 mins',
        details: [
            'Applicable for both window or split ACs',
            'Indoor unit deep cleaning with foam & jet spray',
        ],
        category: 0,
    },
    {
        id: 3,
        title: 'Foam-jet service (4 ACs)',
        badge: '4 ACs PACK',
        image: '/images/ac4.jpg',
        rating: 4.77,
        reviews: '1.7M',
        price: 1996,
        originalPrice: 2396,
        perAcPrice: 499,
        timeRequired: '3 hrs',
        details: [
            'Applicable for both window or split ACs',
            'Indoor unit deep cleaning with foam & jet spray',
        ],
        category: 0,
    },
    {
        id: 4,
        title: 'Foam-jet service (5 ACs)',
        badge: '5 ACs PACK',
        image: '/images/ac5.jpg',
        rating: 4.77,
        reviews: '1.7M',
        price: 2495,
        originalPrice: 2995,
        perAcPrice: 499,
        timeRequired: '3 hrs 45 mins',
        details: [
            'Applicable for both window or split ACs',
            'Indoor unit deep cleaning with foam & jet spray',
        ],
        category: 0,
    },
    // Add more services for other categories as needed
    // Repair & gas refill (category: 2)
    {
        id: 10,
        title: 'AC less/no cooling repair',
        badge: 'NO COOLING',
        image: '/images/ac-repair1.jpg',
        rating: 4.77,
        reviews: '463K',
        price: 299,
        originalPrice: 0,
        perAcPrice: 299,
        timeRequired: '2 hrs 30 mins',
        details: [
            'Applicable for both window & split ACs',
        ],
        category: 2,
    },
    {
        id: 11,
        title: 'AC power issue repair',
        badge: 'NO POWER',
        image: '/images/ac-repair2.jpg',
        rating: 4.75,
        reviews: '122K',
        price: 299,
        originalPrice: 0,
        perAcPrice: 299,
        timeRequired: '60 mins',
        details: [
            'Applicable for both window & split ACs',
        ],
        category: 2,
    },
    {
        id: 12,
        title: 'AC noise/smell repair',
        badge: 'NOISE & ODOUR',
        image: '/images/ac-repair2.jpg',
        rating: 4.79,
        reviews: '35K',
        price: 499,
        originalPrice: 0,
        perAcPrice: 499,
        timeRequired: '60 mins',
        details: [
            'Applicable for both window & split ACs',
        ],
        category: 2,
    },
    {
        id: 13,
        title: 'AC water leakage repair',
        badge: 'WATER LEAKAGE',
        image: '/images/ac-repair2.jpg',
        rating: 4.74,
        reviews: '138K',
        price: 619,
        originalPrice: 0,
        perAcPrice: 619,
        timeRequired: '60 mins',
        details: [
            'Applicable for both window & split ACs',
        ],
        category: 2,
    },

    {
        id: 14,
        title: 'Gas refill & check-up',
        badge: 'WATER LEAKAGE',
        image: '/images/ac-repair-gasrefill.jpg',
        rating: 4.80,
        reviews: '122K',
        price: 2500,
        originalPrice: 0,
        perAcPrice: 2500,
        timeRequired: '2 hrs 30 mins',
        details: [
            'Applicable for both window & split ACs',
        ],
        category: 2,
    },

    {
        id: 20,
        title: 'Foam-jet AC service',
        badge: '',
        image: '/images/ac2.jpg',
        rating: 4.77,
        reviews: '1.7M',
        price: 599,
        originalPrice: 0,
        perAcPrice: 599,
        timeRequired: '',
        details: [
            'Applicable for both window & split ACs',
            'Indoor unit deep cleaning with foam & jet spray',
        ],
        category: 1,
        options: 6,
        savePercent: 17,
        highlight: 'Add more & save up to 17%'
    },
    // Installation/uninstallation (category: 3)
    {
        id: 30,
        title: 'Split AC installation',
        badge: '',
        image: '/images/split-ac-install.jpg',
        rating: 4.71,
        reviews: '106K',
        price: 1499,
        originalPrice: 0,
        perAcPrice: 1499,
        timeRequired: '2 hrs 30 mins',
        details: [],
        category: 3,
    },
    {
        id: 31,
        title: 'Window AC installation',
        badge: '',
        image: '/images/window-ac-install.jpg',
        rating: 4.81,
        reviews: '13K',
        price: 1099,
        originalPrice: 0,
        perAcPrice: 1099,
        timeRequired: '2 hrs 30 mins',
        details: [],
        category: 3,
    },
    {
        id: 32,
        title: 'Split AC uninstallation',
        badge: '',
        image: '/images/split-ac-uninstall.jpg',
        rating: 4.83,
        reviews: '108K',
        price: 899,
        originalPrice: 0,
        perAcPrice: 899,
        timeRequired: '60 mins',
        details: [],
        category: 3,
    },
    {
        id: 33,
        title: 'Window AC uninstallation',
        badge: '',
        image: '/images/window-ac-uninstall.jpg',
        rating: 4.87,
        reviews: '11K',
        price: 699,
        originalPrice: 0,
        perAcPrice: 699,
        timeRequired: '60 mins',
        details: [],
        category: 3,
    },
]; 